### ISSUE TITLE
Sourcemaps JS | CSS

### ISSUE THREAD

**Issue by lincolnlemos** [ixkaito/bathe#8]
How are you handling the js source maps?

I noticed that you can set the "outputStyle" to CSS, but for JS I'm lost.

**Comment by akiya64** [comment]
Hi.
If you do not need compress by uglify at `gulp webpack` task, webpack can generate SourceMap.

1.  Comment out `.pipe(uglify())` or remove this row in [bathe/gulp_tasks/webpack.js](https://github.com/ixkaito/bathe/blob/master/gulp_tasks/webpack.js) file.
2. Add webpack settings `devtool: 'source-map'` in [bathe.config.js](https://github.com/ixkaito/bathe/blob/master/bathe.config.js)
like this

```
  webpack: {
    mode:   'production',
    devtool: 'source-map',
    module: {
      rules: [],
    },
```
3. Run `gulp webpack`, generate js and js.map files in /assets/js dir.

I tried generate SourceMap by [gulp-sourcemaps](https://www.npmjs.com/package/gulp-sourcemaps), keeping another plugins.
But I cannot generate sourcemap.

**Comment by ixkaito** [comment]
@lincolnlemos Sorry for the late reply. On the [latest release](https://github.com/ixkaito/bathe/releases/tag/v0.5.3), I removed `gulp-uglify` because Webpack automaticly compress js files now. Or you can just remove the `.pipe(uglify())` line in gulp_tasks/webpack.js.

As @akiya64's comment, adding `devtool: 'source-map'` will generate js source maps when you run `npm start`.

Thanks @akiya64 .

**Comment by ixkaito** [comment]
This was totally updated in v1.0, so I will close this issue.
