### ISSUE TITLE
Webpack

### ISSUE THREAD

**Issue by tan-ahmed** [ixkaito/bathe#9]
Hi

Fantastic starter theme, I've been using it for over a year now.

This isn't an issue, but I was wondering when would you eventually just use webpack?
I noticed Webpack can already do what gulp does, so gulp seems a bit redundant at this point surely?

Thanks.

**Comment by ixkaito** [comment]
Hi, @tan-ahmed. Thanks for using this project. You're right. Webpack can do almost what gulp does. Before, webpack could only bundle css into js files, and I didn't like that solution. But now, webpack (with a plugin) can output css and js files separately. Maybe it's about time to remove gulp.

You know, it'll be a hard work to remove gulp. I've recommended to use npm scripts; in that case, gulp was encapsulated in the black box. Usually whether gulp or webpack doesn't affect users. That's why I hesitate to remove gulp. But pull requests are really welcome :)

**Comment by ixkaito** [comment]
@tan-ahmed I removed gulp and integrated all tasks into npm-scripts in v1.0. Take a look at it.
